openapi: 3.0.3
info:
  version: 1.0.0
  title: densityAPI
  description: Api for retrieving density info 
  x-sla:
    $ref: ./plans.yaml
security:
  - BearerAuth: []
paths:
  /api/v1/density:
    x-router-controller: densityController
    get:
      description: Returns all density
      operationId: getDensitys
      responses:
        200:
          description: density list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/density'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
                  
  /api/v1/density/{year}:
    x-router-controller: densityController
    get:
      description: Returns a single density by its year
      operationId: findByyear
      parameters:
        - required: true
          name: year
          description: id of the team to fetch
          in: path
          schema:
            type: number
      responses:
        200:
          description: density found by id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/density'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    density:
        type: object
        required:
          - year
        properties:
          year:
            type: number
          province:
            type: string
          gender:
            type: string
          municipality_size_lt_ft:
            type: number
          municipality_size_bt_ft_tht:
            type: number
          municipality_size_gt_tht:
            type: number
          capital_size:
            type: number
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
      additionalProperties: true